CREATE TABLE [dbo].[Reservations] (
    [Id]                UNIQUEIDENTIFIER CONSTRAINT [DF__Reservations__Id__4A8310C6] DEFAULT (newid()) NOT NULL,
    [RestaurantId]      UNIQUEIDENTIFIER NOT NULL,
    [PaxCount]          SMALLINT         NOT NULL,
    [BookingTime]       DATETIME         NOT NULL,
    [BookingStatusId]   UNIQUEIDENTIFIER NOT NULL,
    [CustomerId]        UNIQUEIDENTIFIER NOT NULL,
    [SpecialOccasionId] UNIQUEIDENTIFIER NULL,
    [ConfirmedAt]       DATETIME         NULL,
    [ConfirmedBy]       UNIQUEIDENTIFIER NULL,
    [CanceledAt]        DATETIME         NULL,
    [CanceledBy]        UNIQUEIDENTIFIER NULL,
    [CancelReasonId]    UNIQUEIDENTIFIER NULL,
    [FinalPaxCount]     SMALLINT         NULL,
    [InvoiceId]         UNIQUEIDENTIFIER NULL,
    [IsActive]          BIT              CONSTRAINT [DF__Reservati__IsAct__4B7734FF] DEFAULT ((1)) NOT NULL,
    [CreatedAt]         DATETIME         CONSTRAINT [DF__Reservati__Creat__4C6B5938] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]         NVARCHAR (100)   NOT NULL,
    [UpdatedAt]         DATETIME         NULL,
    [UpdatedBy]         NVARCHAR (100)   NULL,
    [DeletedAt]         DATETIME         NULL,
    [DeletedBy]         NVARCHAR (100)   NULL,
    CONSTRAINT [PK__Reservat__3214EC07E0C0A37A] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Reservations_BookingStatuses_BookingStatusId] FOREIGN KEY ([BookingStatusId]) REFERENCES [mst].[BookingStatuses] ([Id]),
    CONSTRAINT [FK_Reservations_CancelReasons_CancelReasonId] FOREIGN KEY ([CancelReasonId]) REFERENCES [mst].[CancelReasons] ([Id]),
    CONSTRAINT [FK_Reservations_Customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([Id]),
    CONSTRAINT [FK_Reservations_Employees_CanceledBy] FOREIGN KEY ([CanceledBy]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Reservations_Employees_ConfirmedBy] FOREIGN KEY ([ConfirmedBy]) REFERENCES [dbo].[Employees] ([Id]),
    CONSTRAINT [FK_Reservations_Invoices] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoices] ([Id]),
    CONSTRAINT [FK_Reservations_Restaurants_RestaurantId] FOREIGN KEY ([RestaurantId]) REFERENCES [dbo].[Restaurants] ([Id]),
    CONSTRAINT [FK_Reservations_SpecialOccasions_SpecialOccasionId] FOREIGN KEY ([SpecialOccasionId]) REFERENCES [mst].[SpecialOccasions] ([Id])
);

