CREATE TABLE [dbo].[Restaurants] (
    [Id]                    UNIQUEIDENTIFIER CONSTRAINT [DF__Restaurants__Id__151B244E] DEFAULT (newid()) NOT NULL,
    [Name]                  NVARCHAR (1000)  NOT NULL,
    [PhoneNumber]           NVARCHAR (255)   NOT NULL,
    [Email]                 NVARCHAR (255)   NOT NULL,
    [Description]           NVARCHAR (MAX)   NOT NULL,
    [IsTemporarilyClosed]   BIT              CONSTRAINT [DF__Restauran__Tempo__160F4887] DEFAULT ((0)) NOT NULL,
    [AvgMinCost]            SMALLINT         NULL,
    [AvgMaxCost]            SMALLINT         NULL,
    [SeatingCapacity]       INT              NULL,
    [IsBuffetAvailable]     BIT              NOT NULL,
    [PublicTransport]       NVARCHAR (1000)  NULL,
    [Parking]               NVARCHAR (1000)  NULL,
    [AdditionalInformation] NVARCHAR (MAX)   NULL,
    [LoyaltyPrograms]       NVARCHAR (1000)  NULL,
    [PointOfInterest]       NVARCHAR (1000)  NULL,
    [LandMark]              NVARCHAR (1000)  NULL,
    [AddressLine1]          NVARCHAR (500)   NOT NULL,
    [AddressLine2]          NVARCHAR (500)   NULL,
    [City]                  NVARCHAR (255)   NOT NULL,
    [StateId]               UNIQUEIDENTIFIER NOT NULL,
    [Latitude]              DECIMAL (14, 10) NOT NULL,
    [Longitude]             DECIMAL (14, 10) NOT NULL,
    [IsActive]              BIT              CONSTRAINT [DF__Restauran__IsAct__17036CC0] DEFAULT ((1)) NOT NULL,
    [CreatedAt]             DATETIME         CONSTRAINT [DF__Restauran__Creat__17F790F9] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]             NVARCHAR (100)   NOT NULL,
    [UpdatedAt]             DATETIME         NULL,
    [UpdatedBy]             NVARCHAR (100)   NULL,
    [DeletedAt]             DATETIME         NULL,
    [DeletedBy]             NVARCHAR (100)   NULL,
    CONSTRAINT [PK__Restaura__3214EC07015290EA] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Restaurants_States_StateId] FOREIGN KEY ([StateId]) REFERENCES [mst].[States] ([Id]) ON DELETE CASCADE
);

