name: Build DACPAC

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-dacpac:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1

    - name: Build SQL project
      run: msbuild DinnerTable.Database.sqlproj /p:Configuration=Debug /t:Build

    - name: Debug: list out artifacts
      run: |
          cmd /C "dir /s /b .\bin\Debug\*.dacpac"
          # or, in PowerShell:
          # Get-ChildItem -Path .\bin\Debug -Recurse -Filter *.dacpac | ForEach-Object Name

    - name: Upload DACPAC artifact
      uses: actions/upload-artifact@v4
      with:
        name: DinnerTable.Database.dacpac
        path: /*.dacpac
